score_counter/counter/urls.py
from django.conf.urls import url
from . import views

app_name = 'counter'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<stu_num>[0-9]+)/$', views.detail, name='detail'),
    url(r'submit/$', views.submit, name='submit'),
    url(r'^(?P<stu_num>[0-9]+)/result/$', views.result, name='result'),
    url(r'^getmajor/$',views.getmajor, name='getmajor'),
    url(r'^(?P<stu_num>[0-9]+)/rebuild/$', views.major_rebuild, name='major_rebuild'),
    url(r"guide/$", views.guide, name='guide'),
]

score_counter/score_counter/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cm/', include('counter.urls')),
    url(r'^$', include('counter.urls')),
]

score_counter/counter/models.py
from django.db import models

# Create your models here.
class MajorManager(models.Manager):
    def get_all(self):
        from django.db import connection
        with connection.cursor() as cursor:
            cursor.execute('''
                SELECT * FROM counter_major
                ''')
            result_list = []
            for row in cursor.fetchall():
                p = self.model(college_num=row[0],year=row[1],college=row[2], \
                               number=row[3],name=row[4],score_pub=row[5],score_core=row[6], \
                               score_sele=row[7],score_dev=row[8],ps=row[9])
                result_list.append(p)
        return result_list

    def get_scorerequest(self,class_num):
        from django.db import connection
        with connection.cursor() as cursor:
            cursor.execute('''
                        SELECT * FROM counter_major WHERE number=%d
                        '''%class_num)
            for row in cursor.fetchall():
                p = self.model(score_pub=row[5], score_core=row[6],score_sele=row[7], score_dev=row[8], ps=row[9])
        return p

class DetailManager(models.Manager):
    def get_all(self):
        from django.db import connection
        with connection.cursor() as cursor:
            cursor.execute('''
                SELECT * FROM counter_detail
                ''')
            result_list = []
            for row in cursor.fetchall():
                p = self.model(id=row[0], number=row[1], name=row[2], point=row[3], \
                               type=row[4], class_num=row[5],if_complete=row[6])
                result_list.append(p)
        return result_list

class ScoreManager(models.Manager):
    def get_all(self):
        from django.db import connection
        with connection.cursor() as cursor:
            cursor.execute('''
                SELECT * FROM counter_score
                ''')
            result_list = []
            for row in cursor.fetchall():
                # p = self.model(id=row[0], term=row[1], number=row[2], name=row[3], type_c=row[12], \
                #                point=row[4], get_point=row[5], grade=row[6], gpa=row[7], \
                #                gpa_t=row[8], type=row[9],stu_num=row[10],class_num=row[11])
                result_list.append(row)
        return result_list

    def score_init(self,row,stu_name):
        obj = Score.objects.filter(stu_num=row[-2],term=row[0],number=row[1])
        if len(obj)==0:
            Score.objects.create(term=row[0], number=row[1], name=row[2], type_c=row[3],\
                       point=row[4], get_point=row[5], grade=row[6], gpa=row[7],\
                       gpa_t=row[8], stu_num=row[-2], class_num=row[-1],stu_name=stu_name,type=3)
        else:
            obj.update(type=3,class_num=row[-1],stu_name=stu_name)
        return 1

    def get_gpa(self,stu_num):
        result = Score.objects.filter(stu_num=stu_num)
        point = sum(i.point for i in result)
        gpa_total = sum(i.gpa_t for i in result)
        return gpa_total/point

class MajorScoreManager(models.Manager):
    def get_all(self):
        from django.db import connection
        with connection.cursor() as cursor:
            cursor.execute('''
                SELECT * FROM counter_majorscore
                ''')
            result_list = []
            for row in cursor.fetchall():
                p = self.model(id=row[0], lesson_num=row[1], lesson_name=row[2], point=row[3], type=row[4], \
                               class_num=row[5], stu_num=row[6], grade=row[7], if_complete=row[8])
                result_list.append(p)
        return result_list

    def majorscore_init(self,stu_number,class_number):
        request_list = Detail.objects.filter(class_num=class_number)
        MajorScore.objects.filter(stu_num=stu_number).delete()
        for item in request_list:
        #     obj = MajorScore.objects.filter(lesson_num=item.number, lesson_name=item.name, stu_num=stu_number)
        #     if len(obj)==0:
            MajorScore.objects.create(lesson_num=item.number, lesson_name=item.name, point=item.point,\
                                       type=item.type, class_num=class_number, stu_num=stu_number,\
                                       if_complete=0)
        #     else:
        #         obj.update(grade=0,if_complete=0)
        return 1

    def majorscore_join(self,stu_number):
        request_list = MajorScore.objects.filter(stu_num=stu_number,type__lte=2)
        for item in request_list:
            if item.lesson_num=='53000100':
                continue
            a = []
            com = 1
            grades = Score.objects.filter(number__contains=item.lesson_num[:6],stu_num=stu_number)
            if not len(grades)==0:
                for i in grades:
                    a.append(i.grade)
                    Score.objects.filter(id=i.id).update(type=item.type)
            else:
                a = [0]
            if min(a)=='F' or min(a)==0:
                com = 0
            MajorScore.objects.filter(id=item.id).update(grade=min(a), if_complete=com)
        pe_list = MajorScore.objects.filter(lesson_num='53000100',stu_num=stu_number)
        pe_grades = Score.objects.filter(number__startswith='530001',stu_num=stu_number)
        for i in range(len(pe_grades)):
            com = 1
            try:
                id = pe_list[i].id
            except:
                continue
            gra = pe_grades[i]
            if gra=='F' or gra==0:
                com = 0
            MajorScore.objects.filter(id=id).update(grade=gra.grade,if_complete=com)
            Score.objects.filter(id=gra.id).update(type=1)
        return 1

class Major(models.Model):
    college_num = models.IntegerField()
    year = models.IntegerField()
    college = models.TextField()
    number = models.IntegerField(primary_key=True)
    name = models.TextField()
    score_pub = models.FloatField()
    score_core = models.FloatField()
    score_sele = models.FloatField()
    score_dev = models.FloatField()
    ps = models.TextField(null=True)
    objects = MajorManager()

    def export(self):
        self.data = [self.college_num,self.year,self.college,self.number,self.name, \
                self.score_pub,self.score_core,self.score_sele,self.score_dev,self.ps]
        return self.data

    def __str__(self):
        self.export()
        this_str = ''
        for i in range(0,5):
            this_str = this_str + str(self.data[i])+' '
        return this_str

class Detail(models.Model):
    id = models.IntegerField(primary_key=True)
    number = models.CharField(max_length=10)
    name  = models.TextField()
    point = models.FloatField()
    type = models.IntegerField()
    class_num = models.IntegerField()
    if_complete = models.BooleanField(default=0)
    objects = DetailManager()

    def export(self):
        self.data = [self.id,self.number,self.name,self.point,self.type,self.class_num]
        return self.data

    def __str__(self):
        self.export()
        this_str = ''
        for item in self.data:
            this_str = this_str+str(item) +' '
        return this_str


class Score(models.Model):
    id = models.IntegerField(primary_key=True)
    term = models.IntegerField()
    number = models.CharField(max_length=10)
    name = models.TextField()
    type_c = models.TextField()
    point = models.FloatField()
    get_point = models.FloatField()
    grade = models.CharField(max_length=3)
    gpa = models.FloatField()
    gpa_t = models.FloatField()
    type = models.IntegerField()
    stu_num = models.IntegerField()
    class_num = models.IntegerField()
    stu_name = models.CharField(max_length=10,default=' ')
    objects = ScoreManager()

    def export(self):
        self.data = [self.term,self.number,self.name,self.type_c,self.point, \
                self.get_point,self.grade,self.gpa,self.gpa_t,self.stu_num,self.class_num]
        return self.data

    def __str__(self):
        self.export()
        this_str = ''
        for i in range(0,11):
            this_str = this_str + str(self.data[i])+' '
        return this_str

class MajorScore(models.Model):
    id = models.IntegerField(primary_key=True)
    lesson_num = models.CharField(max_length=10)
    lesson_name = models.TextField()
    point = models.FloatField()
    type = models.IntegerField()
    class_num = models.IntegerField()
    stu_num = models.IntegerField()
    grade = models.CharField(max_length=3, null=False)
    if_complete = models.BooleanField(default=0)
    objects = MajorScoreManager()

score_counter/counter/views.py
# -*- coding:utf-8 -*-
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.db import connection,Error
from .models import Major,Detail,Score,MajorScore
import json

# Create your views here.

def index(request):
    return render(request, 'index.html')

def guide(request):
    return render(request, 'guide.html')

def submit(request):
    delta = 1
    #成绩单内容获取，并分割，内容中主要存在空格和制表符\t
    gpa_content = request.POST['content']
    #大学英语中“A level”的空格会影响分割
    if gpa_content.find('\t'):
        gpa_content = gpa_content.replace('\t', '\r\n')
        delta = 0
    gpa_content = gpa_content.replace(' level','level').replace(':',' ').replace('\r\n',' ').replace('  ', ' ')

    gpa_content = gpa_content.split(' ')
    #粗略判断内容是否为成绩表，否则提示error
    # try:
    # index = gpa_content.index('绩点')
    index = gpa_content.index('姓名')
    # except ValueError:
    #     return render(request, 'index.html', {'error_message': "同学！你是不是复制错了？看看说明吧",
    #                                           'gpa_content':gpa_content,})
    stu_number = gpa_content[index-1]
    stu_name = gpa_content[index+1]
    stu_class_name = gpa_content[index+5]
    major = Major.objects.filter(name=stu_class_name,year=stu_number[0:4])[0]
    #成绩单内容以学期分割
    try:
        result_list = spilt_by_term(gpa_content, stu_number)
    except ValueError:
        return render(request, 'index.html', {'error_message': "同学！你是不是复制错了？看看说明吧",
                                              'gpa_content': gpa_content, })
    #课程条目插入数据库
    score_insert(result_list,stu_number,major.number,stu_name)
    return HttpResponseRedirect(reverse('counter:detail', args=(stu_number,)))

def detail(request,stu_num):
    stu_num = int(stu_num)
    a = Score.objects.filter(stu_num=stu_num)[0]
    stu_class_num = a.class_num
    stu_name = a.stu_name
    major = Major.objects.get(number=stu_class_num)
    MajorScore.objects.majorscore_init(stu_num,stu_class_num)
    result_list = MajorScore.objects.filter(stu_num=stu_num)
    range1 = {1:'公共必修课程',2:'专业核心课程',3:'专业选修课程'}
    context = {
        'result_list': result_list,
        'range': range1,
        'name': stu_name,
        'score_request': major,
        'stu_number':stu_num,
    }
    return render(request, 'detail.html', context)

def result(request,stu_num):
    double1 = False
    MajorScore.objects.majorscore_join(stu_num)
    result_list = MajorScore.objects.filter(stu_num=stu_num,type__lte=2)
    score_request = Major.objects.get_scorerequest(result_list[0].class_num)
    sele_list = Score.objects.filter(type=3,stu_num=stu_num)
    stu_name = sele_list[0].stu_name
    sele_total = sum(i.get_point for i in sele_list)
    sele_less =  score_request.score_sele - sele_total
    if sele_less<0:
        double1 = True
    gpa = Score.objects.get_gpa(stu_num)
    context={
        'name': stu_name,
        'result_list': result_list,
        'range': {1:'公共必修课程',2:'专业核心课程'},
        'sele_list':sele_list,
        'score_request': score_request,
        'sele_total': sele_total,
        'double1': double1,
        'less': sele_less,
        'gpa':("%.2f"%gpa),
    }
    return render(request, 'result.html', context)

def getmajor(request):
    year = request.POST['year']
    college = request.POST['college']
    major = Major.objects.filter(year=year,college_num=college)
    major_list = {}
    for i in range(len(major)):
        major_list[i] = {"id":major[i].number,"name":major[i].name}
    return HttpResponse(json.dumps(major_list), content_type="application/json")

def major_rebuild(request, stu_num):
    major_num = request.POST['major']
    Score.objects.filter(stu_num=stu_num).update(class_num=major_num)
    MajorScore.objects.filter(stu_num=stu_num).delete()
    return HttpResponseRedirect(reverse('counter:detail', args=(stu_num,)))


#将分割成列表的成绩表以学期为单位分割
def spilt_by_term(content_list, item):
    result_list = []
    lesson_single = []
    #将内容列表中为学号的位置点全部找出
    all_point = [i for i, j in enumerate(content_list) if j == item]
    all_point.append(int(-1))
    #将列表中课程条目部分切出，
    for i in range(len(all_point)-1):
        a = all_point[i]
        b = all_point[i+1]
        result_list.append(content_list[a:b])
    for i in range(len(result_list)):
        #num_of_col用于判断每一行的栏目数
        #因为发现有部分同学某个学期的成绩表会多出一列
        #所以干脆做一个判断
        point1 = result_list[i].index('序号')
        start = result_list[i].index('备注')
        num_of_col = start-point1
        #避免成绩表格式导致索引出错
        #一般“备注”后会有一个空值，但发现有些浏览器渲染出来的内容格式有区别，其后可能出现若干个空置
        for x in range(0,10):
            if result_list[i][start+x]=='1':
                start = start + x
                break
        try:
            end = result_list[i].index('所选学分')
        except ValueError:
            end = result_list[i].index('取得学分')-2
        term = result_list[i][start:end]
        #这里将课程逐条切出
        #['序号','学期号','课程号','名称','类别（如必修）','学分','取得学分','成绩(ABCD)',
        # '绩点','学分绩点','备注（一般为空）']
        delta = 0
        if term[10] =='' or term[11]=='':
            delta = 1
        else:
            delta = 0
        num_of_col = num_of_col+delta
        for i in range((len(term)+1)//num_of_col):
            a = term[i*num_of_col:(i+1)*num_of_col]
            if delta==0:
                lesson_single.append(a)
            else:
                lesson_single.append(a[:-1])
    return lesson_single
#
def score_insert(list,stu_num,class_num,stu_name):
    for item in list:
        if item[5]=='必修' or item[5]=='选修':
            del item[5]
        a = item[1:]
        a.append(str(stu_num))
        a.append(str(class_num))
        Score.objects.score_init(a,stu_name)
    return 1

score_counter/counter/templates/bootstrap.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}学分计算器！{% endblock %}</title>

    <!-- Bootstrap -->
    {% load static %}
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/loading.css" %}">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    <script>
      $(document).ready(function(){
          $("#next").click(function(){
              // $("#loading").show();
              $("#loading").fadeIn(500);
          })
      });
    </script>

  </head>
  <body>
    <div id="loading" style="display: none;">
          <div id="loading-center">
              <div id="loading-center-absolute">
                  <div class="object" id="object_one"></div>
                  <div class="object" id="object_two"></div>
                  <div class="object" id="object_three"></div>
                  <div class="object" id="object_four"></div>
              </div>
          </div>
      </div>
    </body>
    <div class="container">
      {% block content %}
      {% endblock %}
</html>

score_counter/counter/templates/detail.html
{% extends "bootstrap.html" %}}

{% block title %}你的培养方案{% endblock %}

{% block content %}
<div class="confirm" style="margin: 50px auto;">
      <h3>{{name}}同学，请确认这是你的培养方案内容</h3>
      <a id="next" href="result/" class="btn btn-primary" role="button">是的没错</a>
      <button id="btn2" class="btn btn-warning">需要修改</button>
    </div>

        {% if score_request %}
            <div class="col-md-8 col-md-offset-2">
                <h3>{{score_request.year}}{{score_request.name}}</h3>
                <h4  style="margin-top: 40px">毕业学分要求</h4>
            <table class="table table-striped table-condensed">
                <tr>
                    <td>公共必修学分</td><td>专业核心课</td><td>选修课</td><td>创新实践学分</td>
                </tr>
                <tr>
                    <td>{{score_request.score_pub}}</td>
                    <td>{{score_request.score_core}}</td>
                    <td>{{score_request.score_sele}}</td>
                    <td>{{score_request.score_dev}}</td>
                </tr>
                <tr>
                  <td colspan="4">{{score_request.ps}}</td>
                </tr>
            </table>
            </div>
        {% endif %}
        {% if result_list %}
        {% for key, value in range.items %}
            <div class="col-md-10 col-md-offset-1 ">
                <h3>{{value}}</h3>
            <table class="table table-striped">
                <tr>
                    <td>#</td><td>课程编号</td><td>课程名</td><td>学分</td>
                </tr>
                {% for item in result_list %}
                {% if item.type == key %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{item.lesson_num}}</td>
                    <td style="width: 450px;">{{item.lesson_name}}</td>
                    <td>{{item.point}}</td>
                </tr>
                {% endif %}
                {% endfor %}
            </table>
            <br>
            </div>
        {% endfor %}
        {% endif %}

    </div>
    <div id="major-re" style="display: none;">
        <div id="major-re-center">
          <form action="rebuild/" method="POST">
            {% csrf_token %}
              <label>请选择你的年级：
              <select id="year" class="form-control" name="year" >
              <option value="2016">2016</option>
              <option value="2015">2015</option>
              <option value="2014">2014</option>
              <option value="2013">2013</option>
              </select>
              </label>
              <label>请选择你的学院：
              <select id="collage" class="form-control" name="collage" url="rebuild/">
              <option value="0" name="option0">请选择</option>
              <option value="1" name="option1">人文学院</option>
              <option value="2" name="option2">经济学院</option>
              <option value="3" name="option3">法学院</option>
              <option value="4" name="option4">管理学院</option>
              <option value="5" name="option5">艺术设计学院</option>
              <option value="6" name="option6">高尔夫学院</option>
              <option value="7" name="option7">外国语学院</option>
              <option value="8" name="option8">传播学院</option>
              <option value="9" name="option9">土木工程学院</option>
              <option value="10" name="option10">建筑与城市规划学院</option>
              <option value="11" name="option11">机电与控制工程学院</option>
              <option value="12" name="option12">师范学院</option>
              <option value="13" name="option13">信息工程学院</option>
              <option value="14" name="option14">化学与环境学院</option>
              <option value="15" name="option15">计算机与软件学院</option>
              <option value="16" name="option16">电子科学与技术学院</option>
              <option value="17" name="option17">光电工程学院</option>
              <option value="18" name="option18">物理与能源学院</option>
              <option value="19" name="option19">数学与统计学院</option>
              <option value="20" name="option20">材料学院</option>
              <option value="22" name="option22">医学院</option>
              <option value="24" name="option24">心理与社会学院</option>
              <option value="30" name="option30">生命与海洋科学学院</option>
              </select>
              </label>
              <label>请选择你的专业名：
              <select id="major" class="form-control" name="major">
              <option value="0">请选择</option>
              </select>
              </label>
              <button id="btn1" class="btn btn-primary" type="submit" style="margin-top: -5px;">确认</button>
              <button id="cancel" class="btn btn-warning" type="button" style="margin-top: -5px;">取消</button>
          </form>

        </div>
      </div>
    <script type="text/javascript">
      $(document).ready(function() {
          $("#btn1").click(function () {
              $("#loading").fadeIn(500);
          });
          $("#btn2").click(function () {
              $("#major-re").fadeIn(500);
          });

          $("#cancel").click(function () {
              $("#major-re").fadeOut(500);
          });

          $("#collage").change(function () {
              var year1 = $("#year").val();
              var collage1 = $("#collage").val();
              $.ajaxSetup({
                  data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
              });
              $.ajax({
                  type: 'POST',
                  url: "{% url 'counter:getmajor' %}",
                  data: {
                      "year": year1,
                      "college": collage1
                  },

                  success: function (data) {
                      $("#major").empty();
                      var result = eval(data);
                      $.each(result,function (key,content) {
                          var opt = $("<option></option>").text(content.name).val(content.id);
                          $("#major").append(opt);
                      });
                  }
              });
          });
      });
    </script>
{% endblock %}}

score_counter/counter/templates/index.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>学分计算器！</title>

    <!-- Bootstrap -->
    {% load static %}
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/loading.css" %}">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body style="background: #C9D6FF;  /* fallback for old browsers */
    background: -webkit-linear-gradient(to bottom, #C9D6FF, #E2E2E2);  /* Chrome 10-25, Safari 5.1-6 */
    background: linear-gradient(to bottom, #C9D6FF, #E2E2E2);
">
    <div class="container">
        <div class="main_title">
            <h1>这是一个简单的学分计算器</h1>
            <!--<p class="sub_title">Here is the sub tilte</p>-->
            <h4 class="sub_title">我们花了不少时间，是想为深大的你提供一点方便</h4>
        </div>
        <form class="form col-md-6 col-md-offset-3" action="{% url 'counter:submit' %}" method="POST">
            {% csrf_token %}
            <div class="col-lg-6 index-input">
                <textarea name="content" class="form-control input-form" placeholder="请复制你的成绩表到这里（7.18：作者刚修了两个巨好笑的bug，希望使用有问题的同学可以邮件联系edwardvon246@gmail.com，谢谢啦~）" rows="5"></textarea>
                <button id="next" class="btn btn-primary website-submit" type="submit">GO!</button>

                </div><!-- /input-group -->
              </div><!-- /.col-lg-6 -->
        </form>

        {% if error_message %}
        <div class="message col-md-6 col-md-offset-3">
            <h4 class="text-info "><strong>{{ error_message }}</strong></h4>
        </div>
        {% endif %}
    <div>
        <div class="logo">
        </div>
        <div class="guide col-md-6 col-md-offset-3">
            <a href="{% url 'counter:guide' %}" target="_blank"><h4 style="font-weight: 600;">使用指南</h4></a>
            <a href="http://192.168.2.20/student.aspx" target="_blank"><h5>校园网成绩查询</h5></a>
            <a href="http://edwardvon.ngrok.cc/student.aspx" target="_blank"><h5>非校园网成绩表查询（仅测试）</h5></a>
            <!--<p>&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</p>-->
            <!--<p>Powered by CM & Gwan @ SZU</p>-->
            <!--<p>如有建议或意见，或BUG反馈，请联系edwardvon246@gmail.com</p>-->

        </div>
    </div>
    <div class="just_warpper"></div>
    </div>
    <div id="loading" style="display: none;">
        <div id="loading-center">
            <div id="loading-center-absolute">
                <div class="object" id="object_one"></div>
                <div class="object" id="object_two"></div>
                <div class="object" id="object_three"></div>
                <div class="object" id="object_four"></div>
            </div>
        </div>
    </div>
  </body>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/loading.js" %}"></script>


</html>